#############################################################################
# Makefile for building: PacMan
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  PacMan.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile PacMan.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PacMan1.0.0
DISTDIR = /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/.tmp/PacMan1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/AStar.cpp \
		src/Blinky.cpp \
		src/Character.cpp \
		src/Clyde.cpp \
		src/Collectible.cpp \
		src/GameWindow.cpp \
		src/Ghost.cpp \
		src/Inky.cpp \
		src/Interface.cpp \
		src/Map.cpp \
		src/Pac.cpp \
		src/Pinky.cpp \
		src/Point.cpp \
		src/Scoreboard.cpp \
		src/ScoreboardTable.cpp \
		src/Star.cpp qrc_resources.cpp \
		moc_Blinky.cpp \
		moc_Character.cpp \
		moc_Clyde.cpp \
		moc_GameWindow.cpp \
		moc_Ghost.cpp \
		moc_Inky.cpp \
		moc_Map.cpp \
		moc_Pac.cpp \
		moc_Pinky.cpp \
		moc_Scoreboard.cpp \
		moc_ScoreboardTable.cpp
OBJECTS       = AStar.o \
		Blinky.o \
		Character.o \
		Clyde.o \
		Collectible.o \
		GameWindow.o \
		Ghost.o \
		Inky.o \
		Interface.o \
		Map.o \
		Pac.o \
		Pinky.o \
		Point.o \
		Scoreboard.o \
		ScoreboardTable.o \
		Star.o \
		qrc_resources.o \
		moc_Blinky.o \
		moc_Character.o \
		moc_Clyde.o \
		moc_GameWindow.o \
		moc_Ghost.o \
		moc_Inky.o \
		moc_Map.o \
		moc_Pac.o \
		moc_Pinky.o \
		moc_Scoreboard.o \
		moc_ScoreboardTable.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		PacMan.pro src/AStar.h \
		src/Blinky.h \
		src/Character.h \
		src/Clyde.h \
		src/Collectible.h \
		src/Direction.h \
		src/GameState.h \
		src/GameWindow.h \
		src/Ghost.h \
		src/Inky.h \
		src/Interface.h \
		src/Map.h \
		src/MapState.h \
		src/Pac.h \
		src/Pinky.h \
		src/Point.h \
		src/Scoreboard.h \
		src/ScoreboardTable.h \
		src/Star.h \
		src/Types.h src/AStar.cpp \
		src/Blinky.cpp \
		src/Character.cpp \
		src/Clyde.cpp \
		src/Collectible.cpp \
		src/GameWindow.cpp \
		src/Ghost.cpp \
		src/Inky.cpp \
		src/Interface.cpp \
		src/Map.cpp \
		src/Pac.cpp \
		src/Pinky.cpp \
		src/Point.cpp \
		src/Scoreboard.cpp \
		src/ScoreboardTable.cpp \
		src/Star.cpp
QMAKE_TARGET  = PacMan
DESTDIR       = 
TARGET        = PacMan


first: all
####### Build rules

PacMan:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PacMan.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		PacMan.pro \
		resources.qrc
	$(QMAKE) -o Makefile PacMan.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
PacMan.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile PacMan.pro

qmake_all: FORCE


all: Makefile PacMan

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/AStar.h src/Blinky.h src/Character.h src/Clyde.h src/Collectible.h src/Direction.h src/GameState.h src/GameWindow.h src/Ghost.h src/Inky.h src/Interface.h src/Map.h src/MapState.h src/Pac.h src/Pinky.h src/Point.h src/Scoreboard.h src/ScoreboardTable.h src/Star.h src/Types.h $(DISTDIR)/
	$(COPY_FILE) --parents src/AStar.cpp src/Blinky.cpp src/Character.cpp src/Clyde.cpp src/Collectible.cpp src/GameWindow.cpp src/Ghost.cpp src/Inky.cpp src/Interface.cpp src/Map.cpp src/Pac.cpp src/Pinky.cpp src/Point.cpp src/Scoreboard.cpp src/ScoreboardTable.cpp src/Star.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		assets/inky/inky1.png \
		assets/inky/inky0.png \
		assets/clyde/clyde0.png \
		assets/clyde/clyde1.png \
		assets/blinky/blinky1.png \
		assets/blinky/blinky0.png \
		assets/pinky/pinky1.png \
		assets/pinky/pinky0.png \
		assets/pac/pac5.png \
		assets/pac/pac9.png \
		assets/pac/pac0.png \
		assets/pac/pac4.png \
		assets/pac/pac8.png \
		assets/pac/pac3.png \
		assets/pac/pac7.png \
		assets/pac/pac2.png \
		assets/pac/pac6.png \
		assets/pac/pac1.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Blinky.cpp moc_Character.cpp moc_Clyde.cpp moc_GameWindow.cpp moc_Ghost.cpp moc_Inky.cpp moc_Map.cpp moc_Pac.cpp moc_Pinky.cpp moc_Scoreboard.cpp moc_ScoreboardTable.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Blinky.cpp moc_Character.cpp moc_Clyde.cpp moc_GameWindow.cpp moc_Ghost.cpp moc_Inky.cpp moc_Map.cpp moc_Pac.cpp moc_Pinky.cpp moc_Scoreboard.cpp moc_ScoreboardTable.cpp
moc_Blinky.cpp: src/Blinky.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Blinky.h -o moc_Blinky.cpp

moc_Character.cpp: src/Character.h \
		src/Map.h \
		src/Character.h \
		src/Direction.h \
		src/Collectible.h \
		src/Types.h \
		src/MapState.h \
		src/Interface.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Character.h -o moc_Character.cpp

moc_Clyde.cpp: src/Clyde.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Clyde.h -o moc_Clyde.cpp

moc_GameWindow.cpp: src/GameWindow.h \
		src/Map.h \
		src/Character.h \
		src/Direction.h \
		src/Collectible.h \
		src/Types.h \
		src/MapState.h \
		src/Interface.h \
		src/GameState.h \
		src/Scoreboard.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GameWindow.h -o moc_GameWindow.cpp

moc_Ghost.cpp: src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Ghost.h -o moc_Ghost.cpp

moc_Inky.cpp: src/Inky.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Inky.h -o moc_Inky.cpp

moc_Map.cpp: src/Map.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Map.h -o moc_Map.cpp

moc_Pac.cpp: src/Pac.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Pac.h -o moc_Pac.cpp

moc_Pinky.cpp: src/Pinky.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Pinky.h -o moc_Pinky.cpp

moc_Scoreboard.cpp: src/Scoreboard.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Scoreboard.h -o moc_Scoreboard.cpp

moc_ScoreboardTable.cpp: src/ScoreboardTable.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/mnt/c/Users/Damian/Desktop/coding/UniversityBig/C++/PacMan -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ScoreboardTable.h -o moc_ScoreboardTable.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

AStar.o: src/AStar.cpp src/AStar.h \
		src/Direction.h \
		src/Map.h \
		src/Character.h \
		src/Collectible.h \
		src/Types.h \
		src/MapState.h \
		src/Interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AStar.o src/AStar.cpp

Blinky.o: src/Blinky.cpp src/Blinky.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		src/AStar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Blinky.o src/Blinky.cpp

Character.o: src/Character.cpp src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Character.o src/Character.cpp

Clyde.o: src/Clyde.cpp src/Clyde.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		src/AStar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Clyde.o src/Clyde.cpp

Collectible.o: src/Collectible.cpp src/Collectible.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Collectible.o src/Collectible.cpp

GameWindow.o: src/GameWindow.cpp src/GameWindow.h \
		src/Map.h \
		src/Character.h \
		src/Direction.h \
		src/Collectible.h \
		src/Types.h \
		src/MapState.h \
		src/Interface.h \
		src/GameState.h \
		src/Scoreboard.h \
		src/Pac.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameWindow.o src/GameWindow.cpp

Ghost.o: src/Ghost.cpp src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		src/AStar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ghost.o src/Ghost.cpp

Inky.o: src/Inky.cpp src/Inky.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		src/AStar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Inky.o src/Inky.cpp

Interface.o: src/Interface.cpp src/Interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interface.o src/Interface.cpp

Map.o: src/Map.cpp src/Map.h \
		src/Character.h \
		src/Direction.h \
		src/Collectible.h \
		src/Types.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		src/Point.h \
		src/Blinky.h \
		src/Ghost.h \
		src/Pinky.h \
		src/Inky.h \
		src/Clyde.h \
		src/Star.h \
		src/GameWindow.h \
		src/GameState.h \
		src/Scoreboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Map.o src/Map.cpp

Pac.o: src/Pac.cpp src/Pac.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pac.o src/Pac.cpp

Pinky.o: src/Pinky.cpp src/Pinky.h \
		src/Ghost.h \
		src/Character.h \
		src/Map.h \
		src/Collectible.h \
		src/Types.h \
		src/Direction.h \
		src/MapState.h \
		src/Interface.h \
		src/Pac.h \
		src/AStar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pinky.o src/Pinky.cpp

Point.o: src/Point.cpp src/Point.h \
		src/Collectible.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o src/Point.cpp

Scoreboard.o: src/Scoreboard.cpp src/Scoreboard.h \
		src/ScoreboardTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scoreboard.o src/Scoreboard.cpp

ScoreboardTable.o: src/ScoreboardTable.cpp src/ScoreboardTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScoreboardTable.o src/ScoreboardTable.cpp

Star.o: src/Star.cpp src/Star.h \
		src/Collectible.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Star.o src/Star.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_Blinky.o: moc_Blinky.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Blinky.o moc_Blinky.cpp

moc_Character.o: moc_Character.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Character.o moc_Character.cpp

moc_Clyde.o: moc_Clyde.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Clyde.o moc_Clyde.cpp

moc_GameWindow.o: moc_GameWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameWindow.o moc_GameWindow.cpp

moc_Ghost.o: moc_Ghost.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Ghost.o moc_Ghost.cpp

moc_Inky.o: moc_Inky.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Inky.o moc_Inky.cpp

moc_Map.o: moc_Map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Map.o moc_Map.cpp

moc_Pac.o: moc_Pac.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Pac.o moc_Pac.cpp

moc_Pinky.o: moc_Pinky.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Pinky.o moc_Pinky.cpp

moc_Scoreboard.o: moc_Scoreboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Scoreboard.o moc_Scoreboard.cpp

moc_ScoreboardTable.o: moc_ScoreboardTable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScoreboardTable.o moc_ScoreboardTable.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

